defaultPlacement: end
enableVersioning: true
handle: home
name: Home
propagationMethod: all
siteSettings:
  4563318b-ea8b-4b80-bab2-bd315c0f22ba: # craft cms
    enabledByDefault: true
    hasUrls: true
    template: index
    uriFormat: __home__
type: single
